require('dotenv').config()

const PORT = process.env.PORT

const MONGO_URI = process.env.MONGO_URI

const ADMIN_EMAIL = process.env.ADMIN_EMAIL
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD

const REDIS_ENDPOINT_URI = process.env.REDIS_ENDPOINT_URI
const REDIS_PORT = process.env.REDIS_PORT
const REDIS_USERNAME = process.env.REDIS_USERNAME
const REDIS_PASSWORD  = process.env.REDIS_PASSWORD

const EMAIL_HOST = process.env.EMAIL_HOST
const EMAIL_PORT = process.env.EMAIL_PORT

const JWT_EXPIRY_TIME = process.env.JWT_EXPIRY_TIME

const SERVER_ADMIN_EMAIL = process.env.SERVER_ADMIN_EMAIL

const SERVER_NAME = process.env.SERVER_NAME

module.exports = { PORT, MONGO_URI, ADMIN_EMAIL, ADMIN_PASSWORD, REDIS_ENDPOINT_URI, REDIS_PORT, REDIS_USERNAME, REDIS_PASSWORD, EMAIL_HOST, EMAIL_PORT, JWT_EXPIRY_TIME, SERVER_ADMIN_EMAIL, SERVER_NAME }